[package]
name = "numbrs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"        # For Float trait
ndarray = "0.15"   # Optional: For advanced array ops
num-traits = "0.2.19"

[dev-dependencies]
criterion = "0.4"  # For benchmarks
